(()=>{
  document.title='SaveFlow Cashback V53';

  // V53.1 header cleanup: remove leaked developer comment and old subtitle.
  const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
  const removeTextNodes=[];
  while(walker.nextNode()){
    const n=walker.currentNode;
    if((n.nodeValue||'').includes('V25 data additions:')) removeTextNodes.push(n);
  }
  removeTextNodes.forEach(n=>n.remove());
  document.querySelectorAll('body *').forEach(el=>{
    if(el.children.length===0 && (el.textContent||'').trim()==='кешбеки українських банків') el.remove();
  });

  const css=`
.scanner-card{width:min(920px,100%)}.scanner-head{padding-right:34px}.scanner-copy{max-width:720px}
.scanner-summary{border:1px solid var(--line);border-radius:16px;padding:14px 15px;background:#fbfaf7;display:grid;gap:6px;margin:16px 0 14px}
.scanner-summary-title{display:flex;align-items:center;gap:9px;flex-wrap:wrap;font-size:15px;font-weight:850;letter-spacing:-.02em}.scanner-summary-dot{width:10px;height:10px;border-radius:999px;display:inline-block;background:#8a8f88;box-shadow:0 0 0 4px rgba(138,143,136,.12)}
.scanner-summary.success .scanner-summary-dot{background:#3f7f59;box-shadow:0 0 0 4px rgba(63,127,89,.12)}.scanner-summary.warn .scanner-summary-dot{background:#b27b17;box-shadow:0 0 0 4px rgba(178,123,23,.14)}.scanner-summary.error .scanner-summary-dot{background:#b24f4f;box-shadow:0 0 0 4px rgba(178,79,79,.12)}
.scanner-summary-meta{font-size:10px;color:#5d645d;line-height:1.5}.scanner-summary-sub{font-size:9.5px;color:#818782;line-height:1.45}.scanner-actions{margin:0 0 14px}.scanner-actions .matrix-btn.primary{padding-inline:15px}
.scanner-quick-stats{display:flex;gap:8px;flex-wrap:wrap}.scanner-pill{background:#fff}.scanner-details{border:1px solid var(--line);border-radius:14px;background:#fff;overflow:hidden;margin-bottom:16px}.scanner-details summary{list-style:none;cursor:pointer;padding:11px 14px;font-size:10px;font-weight:760;display:flex;align-items:center;justify-content:space-between;gap:12px}.scanner-details summary::-webkit-details-marker{display:none}.scanner-details summary::after{content:'▾';font-size:10px;color:#707670}.scanner-details[open] summary::after{content:'▴'}
.scanner-details-body{padding:0 14px 14px;display:grid;gap:10px}.scanner-legend{font-size:9px;color:#7a817a;line-height:1.5}.scanner-review-title{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:4px 0 10px}.scanner-review-title strong{font-size:12px;letter-spacing:-.015em}.scanner-review-title span{font-size:9.5px;color:var(--muted)}
.scanner-empty{padding:30px 14px;text-align:center;color:#707770;font-size:10px;border:1px dashed #d9d6ce;border-radius:14px;background:#fbfaf7;line-height:1.6}.scanner-empty strong{display:block;color:#323732;font-size:12px;margin-bottom:5px}.scanner-item{gap:10px}.scanner-item-title strong{font-size:12px}.scanner-item-title span{font-size:9.5px}.scanner-priority{font-size:8px}.scanner-excerpt{font-size:9.25px;max-height:96px}.scanner-item-actions .matrix-btn{padding-inline:11px}.scanner-error{margin-top:10px}@media(max-width:700px){.scanner-summary{padding:13px}.scanner-review-title{display:grid;gap:4px}.scanner-card{padding:17px}}`;
  const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);

  const oldModal=document.getElementById('scannerModal');
  if(!oldModal)return;
  const wrap=document.createElement('div');
  wrap.innerHTML=`<div aria-hidden="true" class="scanner-modal" id="scannerModal"><div aria-modal="true" class="scanner-card" role="dialog"><button aria-label="Закрити" class="matrix-modal-close" id="scannerClose" type="button">×</button><div class="scanner-head"><div><div class="auth-kicker">Admin · Моніторинг даних</div><h3>Сканер даних</h3><div class="scanner-copy">Автоматично перевіряє офіційні та контрольні джерела й показує лише ті зміни, які треба переглянути вручну перед оновленням SaveFlow.</div></div></div><div class="scanner-summary" id="scannerSummary"><div class="scanner-summary-title"><span class="scanner-summary-dot"></span><span>Сканер ще не запускався</span></div><div class="scanner-summary-meta">Після першого запуску ми побачимо, чи все актуально, чи є зміни для перевірки.</div><div class="scanner-summary-sub">Остання перевірка: —</div></div><div class="scanner-actions"><button class="matrix-btn primary" id="scannerRun" type="button">Перевірити зараз</button></div><details class="scanner-details" id="scannerDetails"><summary>Технічні деталі</summary><div class="scanner-details-body"><div class="scanner-quick-stats"><span class="scanner-pill">джерел <b id="scannerSourceCount">—</b></span><span class="scanner-pill">очікують перевірки <b id="scannerPendingCount">—</b></span></div><div class="scanner-run" id="scannerLastRun"><strong>Останній запуск</strong><span>Ще немає даних.</span></div><div class="scanner-legend">Тут заховані технічні подробиці для admin: кількість джерел, службовий статус останнього запуску та черга кандидатів.</div><div><button class="matrix-btn" id="scannerRefresh" type="button">Оновити дані</button></div></div></details><div class="scanner-review-title" id="scannerReviewTitle"><strong>Потрібна перевірка</strong><span>Тут з’являються лише реальні сигнали від scanner.</span></div><div class="scanner-list" id="scannerList"></div><div class="scanner-error" id="scannerError"></div></div></div>`;
  oldModal.replaceWith(wrap.firstElementChild);

  const oldToggle=document.getElementById('scannerToggle');
  let openBtn=oldToggle;
  if(oldToggle){openBtn=oldToggle.cloneNode(true);oldToggle.replaceWith(openBtn)}
  const modal=document.getElementById('scannerModal'),closeBtn=document.getElementById('scannerClose'),runBtn=document.getElementById('scannerRun'),refreshBtn=document.getElementById('scannerRefresh'),list=document.getElementById('scannerList'),err=document.getElementById('scannerError'),sourceCount=document.getElementById('scannerSourceCount'),pendingCount=document.getElementById('scannerPendingCount'),lastRun=document.getElementById('scannerLastRun'),summary=document.getElementById('scannerSummary'),reviewTitle=document.getElementById('scannerReviewTitle');
  const esc=v=>String(v??'').replace(/[&<>'\"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[ch]));
  const cloud=()=>{const x=window.saveflowCloud;return x?.client&&x?.session?.user&&x?.profile?.role==='admin'?x:null};
  const close=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')};
  const typeLabel=t=>({reference_to_official_review:'Потрібно звірити reference з official',official_source_changed:'Офіційне джерело змінилося',reference_change_signal:'Контрольне джерело змінилося',dynamic_or_personalized_source_changed:'Dynamic / personalized · ручна перевірка'})[t]||t||'Зміна джерела';
  function runText(r){if(!r)return'<strong>Останній запуск</strong><span>Ще немає даних.</span>';const dt=r.started_at?new Date(r.started_at).toLocaleString('uk-UA'):'—';return`<strong>${esc(r.status||'run')} · ${esc(dt)}</strong><span>джерел: ${Number(r.total_sources||0)} · змін: ${Number(r.changed_sources||0)} · помилок: ${Number(r.failed_sources||0)} · кандидатів: ${Number(r.candidates_created||0)}</span>`}
  function renderSummary(run,totalSources,pending){const last=run?.started_at?new Date(run.started_at).toLocaleString('uk-UA'):'—',total=Number(totalSources||run?.total_sources||0),failed=Number(run?.failed_sources||0),ok=Math.max(total-failed,0);let tone='',title='Сканер ще не запускався',meta='Після першого запуску ми побачимо, чи все актуально, чи є зміни для перевірки.';if(run){if(pending>0){tone='warn';title=`Знайдено ${pending} ${pending===1?'зміну':'зміни'} для перевірки`;meta='Переглянь картки нижче й підтвердь реальні зміни або відхили шум.'}else if(failed>0){tone='error';title='Є проблеми з доступом до частини джерел';meta=`Доступні ${ok} із ${total} джерел. Перевір технічні деталі нижче.`}else{tone='success';title='Усі джерела актуальні';meta=`Доступні ${ok} із ${total} джерел. Нових змін не знайдено.`}}summary.className='scanner-summary'+(tone?' '+tone:'');summary.innerHTML=`<div class="scanner-summary-title"><span class="scanner-summary-dot"></span><span>${esc(title)}</span></div><div class="scanner-summary-meta">${esc(meta)}</div><div class="scanner-summary-sub">Остання перевірка: ${esc(last)}</div>`}
  function renderCandidates(rows){if(!rows?.length){reviewTitle.innerHTML='<strong>Черга змін</strong><span>Поки що все спокійно.</span>';list.innerHTML='<div class="scanner-empty"><strong>Нових змін не знайдено</strong>Якщо банк або інше джерело оновить кешбек, тут з’явиться картка для перевірки.</div>';return}reviewTitle.innerHTML=`<strong>Потрібна перевірка</strong><span>Знайдено ${rows.length} ${rows.length===1?'сигнал':'сигнали'} від scanner.</span>`;list.innerHTML=rows.map(c=>{const affected=Array.isArray(c.affected_cells)?c.affected_cells:[],chips=affected.slice(0,12).map(x=>`<span class="scanner-cell-chip">${esc(x.category||x.cell_key||'клітинка')}${x.current_value?` · ${esc(x.current_value)}`:''}</span>`).join(''),more=affected.length>12?`<span class="scanner-cell-chip">+${affected.length-12}</span>`:'';return`<article class="scanner-item ${esc(c.priority||'normal')}" data-candidate-id="${esc(c.id)}"><div class="scanner-item-top"><div class="scanner-item-title"><strong>${esc(c.bank||c.source_id||'Джерело')}</strong><span>${esc(typeLabel(c.candidate_type))} · ${new Date(c.created_at).toLocaleString('uk-UA')}</span></div><span class="scanner-priority">${esc(c.priority||'normal')}</span></div>${affected.length?`<div class="scanner-affected">${chips}${more}</div>`:''}${c.excerpt?`<div class="scanner-excerpt">${esc(c.excerpt.slice(0,850))}</div>`:''}<div class="scanner-item-actions"><button class="matrix-btn scanner-review" type="button" data-status="reviewed">Підтвердити зміну</button><button class="matrix-btn danger scanner-review" type="button" data-status="rejected">Відхилити</button></div></article>`}).join('');list.querySelectorAll('.scanner-review').forEach(btn=>btn.addEventListener('click',async()=>{const id=btn.closest('[data-candidate-id]')?.dataset.candidateId;if(id)await reviewCandidate(id,btn.dataset.status||'reviewed')}))}
  async function reviewCandidate(id,status){const c=cloud();if(!c)return;const{error}=await c.client.from('scanner_candidates').update({status,reviewed_by:c.session.user.id,reviewed_at:new Date().toISOString()}).eq('id',id);if(error){err.textContent=error.message;return}window.saveflowLogChange?.({scope:'admin',section:'Scanner',action:status==='rejected'?'Відхилено сигнал':'Підтверджено сигнал',target:id});refresh()}
  async function refresh(){const c=cloud();if(!c)return;err.textContent='';const[s,r,p]=await Promise.all([c.client.from('scanner_sources').select('id',{count:'exact'}),c.client.from('scanner_runs').select('*').order('started_at',{ascending:false}).limit(1),c.client.from('scanner_candidates').select('id,source_id,bank,candidate_type,priority,affected_cells,excerpt,status,created_at').eq('status','pending').order('created_at',{ascending:false}).limit(50)]);if(s.error||r.error||p.error){err.textContent=(s.error||r.error||p.error)?.message||'Не вдалося завантажити дані сканера.';return}const total=Number(s.count??s.data?.length??0),pending=Number(p.data?.length??0);sourceCount.textContent=String(total);pendingCount.textContent=String(pending);lastRun.innerHTML=runText(r.data?.[0]);renderSummary(r.data?.[0],total,pending);renderCandidates(p.data||[])}
  async function run(){const c=cloud();if(!c)return;runBtn.disabled=true;runBtn.textContent='Перевіряю…';err.textContent='';try{const{data,error}=await c.client.functions.invoke('scan-sources',{body:{}});if(error)throw error;window.saveflowLogChange?.({scope:'admin',section:'Scanner',action:'Запущено перевірку джерел',target:data?.run_id||''});await refresh()}catch(e){err.textContent=e?.message||String(e)}finally{runBtn.disabled=false;runBtn.textContent='Перевірити зараз'}}
  openBtn?.addEventListener('click',()=>{if(!cloud()){alert('Сканер доступний тільки Admin-акаунту.');return}modal.classList.add('open');modal.setAttribute('aria-hidden','false');refresh()});closeBtn.addEventListener('click',close);refreshBtn.addEventListener('click',refresh);runBtn.addEventListener('click',run);modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))close()});
})();
